name: gradle build
on: [pull_request]
jobs:
  kotlin:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - run: gradle dependencies
      - run: gradle test